In [161]:
import pandas as pd
import numpy as np
df=pd.read_csv('cafe_sales_dirty.csv')

In [162]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [163]:
df_clear=df.dropna()

In [164]:
df_clear

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [165]:
print(f"Duplicate rows found: {df_clear.duplicated().sum()}")

Duplicate rows found: 0

In [166]:
df_clear['Quantity'].dtype

In [167]:
df_clear[['Quantity','Price Per Unit', 'Total Spent']] = df_clear[['Quantity','Price Per Unit', 'Total Spent']].apply(pd.to_numeric, errors='coerce')
df_clear_01=df_clear.dropna(subset=['Quantity','Price Per Unit', 'Total Spent'])

In [168]:
df_clear_01['Quantity'] = df_clear_01['Quantity'].astype(int)

In [169]:
valied_methods = ['Cash','Credit Card','Digital Wallet']
df_clear_01.loc[~df_clear_01['Payment Method'].isin(valied_methods), 'Payment Method'] = np.nan
df_clear_01=df_clear_01.dropna(subset=['Payment Method'])

In [170]:
df_clear_01['Payment Method'].value_counts(dropna=False)

Payment Method
Digital Wallet    1306
Cash              1256
Credit Card       1236
Name: count, dtype: int64

In [171]:
valied_locations = ['In-store','Takeaway']
df_clear_01[~df_clear_01['Location'].isin(valied_locations)]= np.nan
df_clear_01=df_clear_01.dropna(subset=['Location'])

In [172]:
df_clear_01

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,ERROR
...,...,...,...,...,...,...,...,...
9975,TXN_9668108,Cake,1.0,3.0,3.0,Cash,In-store,2023-01-20
9979,TXN_9933628,Smoothie,5.0,4.0,20.0,Cash,In-store,2023-07-20
9986,TXN_2858441,Sandwich,2.0,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3.0,4.0,12.0,Cash,Takeaway,2023-02-24
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [173]:
# Shows a sample of the raw date strings
print(df_clear['Transaction Date'].unique()[:15])

<ArrowStringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-10-06', '2023-10-28', '2023-11-07',      'ERROR', '2023-05-03',
 '2023-11-15', '2023-02-24', '2023-03-25', '2023-01-15', '2023-04-04']
Length: 15, dtype: str

In [174]:
df_clear_01[df_clear_01['Transaction Date'].isin(['ERROR','UNKNOWN'])]=np.nan
df_clear_01=df_clear_01.dropna(subset=['Transaction Date'])

In [175]:
df_clear_01['Transaction Date'] = pd.to_datetime(df_clear_01['Transaction Date'], errors='coerce')

In [176]:
df_clear_01

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
...,...,...,...,...,...,...,...,...
9975,TXN_9668108,Cake,1.0,3.0,3.0,Cash,In-store,2023-01-20
9979,TXN_9933628,Smoothie,5.0,4.0,20.0,Cash,In-store,2023-07-20
9986,TXN_2858441,Sandwich,2.0,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3.0,4.0,12.0,Cash,Takeaway,2023-02-24
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [177]:
print(df_clear_01['Transaction ID'].dtype)

str

In [178]:
# Look at rows that have duplicated Transaction IDs
duplicates = df_clear_01[df_clear_01.duplicated(subset=['Transaction ID'], keep=False)]
print(f"Number of duplicate rows found: {len(duplicates)}")

Number of duplicate rows found: 0

In [179]:
df_clear_01['Transaction ID']=df_clear_01['Transaction ID'].astype(str).str.strip().str.upper()

In [180]:
ID_length = len(df_clear_01['Transaction ID'][10])

In [181]:
wrong_length = df_clear_01[df_clear_01['Transaction ID'].str.len() != ID_length]
print(f"Number of rows with incorrect ID length found: {len(wrong_length)}")

Number of rows with incorrect ID length found: 0

In [182]:
bad_ids = df_clear_01[df_clear_01['Transaction ID'].str.contains('^[A-Z0-9]+$', regex=True)]
print(f"Number of rows with invalid characters in Transaction ID found: {len(bad_ids)}")

Number of rows with invalid characters in Transaction ID found: 0

In [183]:
print("=== 🌟 FINAL CLEAN DATASET PROFILE 🌟 ===")
print(f"Total Rows Remaining: {len(df_clear_01)}")
print(f"Total Columns: {df_clear_01.shape[1]}")
print("\n--- 📊 Data Types & Missing Values ---")
print(df_clear_01.info())

print("\n--- 🧼 Unique Value Verification ---")
print("Payment Methods found:", df_clear_01['Payment Method'].unique())
print("Any Duplicate Transaction IDs?:", df_clear_01.duplicated(subset=['Transaction ID']).any())

=== 🌟 FINAL CLEAN DATASET PROFILE 🌟 ===
Total Rows Remaining: 3308
Total Columns: 8

--- 📊 Data Types & Missing Values ---
<class 'pandas.DataFrame'>
Index: 3308 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3308 non-null   str
 1   Item              3308 non-null   str
 2   Quantity          3308 non-null   float64
 3   Price Per Unit    3308 non-null   float64
 4   Total Spent       3308 non-null   float64
 5   Payment Method    3308 non-null   str
 6   Location          3308 non-null   str
 7   Transaction Date  3308 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 474.2 KB
None

--- 🧼 Unique Value Verification ---
Payment Methods found: <ArrowStringArray>
['Credit Card', 'Cash', 'Digital Wallet']
Length: 3, dtype: str
Any Duplicate Transaction IDs?: False

In [184]:
# Save the cleaned DataFrame to a new CSV file
# index=False prevents Pandas from adding an annoying extra column of row numbers
df_clear_01.to_csv('cleaned_transactions_data.csv', index=False)

print("🚀 Clean CSV successfully saved as 'cleaned_transactions_data.csv'!")

🚀 Clean CSV successfully saved as 'cleaned_transactions_data.csv'!